certification/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import RenderCertificate, searchCertificate, FindView, UpdateUserView, IndexView, DashboardView, AddCoupleView, PaymentView, AddWedView, AddDivorseView, SearchDocumentView, CertificateView, updateStatus

app_name = 'certification'
urlpatterns=[
    path('', IndexView.as_view(), name='home'),
    path('search', searchCertificate, name='search'),
    path('certificate/<str:pk>', CertificateView.as_view(), name='certificates'),
    path('dash/certificate/<str:pk>', RenderCertificate.as_view(), name='render-certificates'),
    path('certificate/<str:pk>/payment', PaymentView.as_view(), name='payment'),
    path('dash', DashboardView.as_view(), name='dashboard'),
    path('add-couple', AddCoupleView.as_view(), name='add-couple'),
    path('add-wed', AddWedView.as_view(), name='add-wed'),
    path('add-divorse', AddDivorseView.as_view(), name='add-divorse'),
    path('profile/<pk>', UpdateUserView.as_view(), name='profile'),
    path('find', FindView.as_view(), name='find'),
    path('certificate/success', updateStatus, name='updatestatus')
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

core/urls.py
from os import name
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.static import serve 
from django.conf import settings
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('certification.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/partiel/base-dash.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Dashboard</title>
            <link rel="stylesheet" href="{% static 'css/style.css'%}">
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
        <script
            src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    </head>
    <body>
        <main>
            <div class="ui two column grid">
                <div class="row ">
                    <div id="side" class="four wide column blue">
                        <div class=" ui centered text avantar">
                            <img class="ui small circular centered image" id="image-profile" src="{% static 'images/avatar-profil.png' %}">
                            
                            <center><p class = "name-profile">Josuebatey19@gmail.com</p></center>
                        </div>
                        <nav>
                            <div class="ui list">
                                <a id="nav-link" class="" href="{% url 'certification:dashboard'%}">
                                    <div class="item" style="">
                                        <i class="home icon" style="font-size:20px; margin-top:10px;"></i>
                                        <div class="content" style="">
                                            Home
                                        </div>
                                    </div>
                                </a>
                                <a id="nav-link" class="" href="{% url 'certification:add-couple'%}">
                                  <div class="item">
                                      <i class="users icon" style="font-size:20px; margin-top:10px;"></i> 
                                      <div class="content " style="">
                                        Add Couple Information
                                      </div>
                                  </div>
                                </a>
                                <a id="nav-link" class="" href="{% url 'certification:add-wed'%}">
                                    <div class="item">
                                        <i class="heart slash icon" style="font-size:20px; margin-top:10px;"></i>
                                        <div class="content" style="">
                                            Wedding Certification
                                        </div>
                                    </div>
                                </a>
                                <a id="nav-link" class="" href="{% url 'certification:add-divorse'%}">
                                    <div class="item">
                                        <i class="home icon" style="font-size:20px; margin-top:10px;"></i>
                                        <div class="content" style="">
                                            Divorse Certification
                                        </div>
                                    </div>
                                </a>
                                <a id="nav-link" class="" href="profile/{{request.user.pk}}">
                                    <div class="item">
                                        <i class="cog icon" style="font-size:20px; margin-top:10px;"></i>
                                        <div class="content" style="">
                                            Profile
                                        </div>
                                    </div>
                                </a>
                                <a id="nav-link" class="" href="{% url 'account_logout'%}">
                                    <div class="item">
                                        <i class="power off icon" style="font-size:20px; margin-top:10px; "></i>
                                        <div class="content" style="">
                                            Logout
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </nav>
                        
                    </div>
                    <div id="main" class="ui container twelve wide column ">
                      {% block content %}
                      {% endblock %}
                    </div>
                </div>
            </div>
                  </main>
    </body>
</html>