certification/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import RenderCertificate, searchCertificate, FindView, UpdateUserView, IndexView, DashboardView, AddCoupleView, PaymentView, AddWedView, AddDivorseView, SearchDocumentView, CertificateView, updateStatus

app_name = 'certification'
urlpatterns=[
    path('', IndexView.as_view(), name='home'),
    path('search', searchCertificate, name='search'),
    path('certificate/<str:pk>', CertificateView.as_view(), name='certificates'),
    path('dash/certificate/<str:pk>', RenderCertificate.as_view(), name='render-certificates'),
    path('certificate/<str:pk>/payment', PaymentView.as_view(), name='payment'),
    path('dash', DashboardView.as_view(), name='dashboard'),
    path('add-couple', AddCoupleView.as_view(), name='add-couple'),
    path('add-wed', AddWedView.as_view(), name='add-wed'),
    path('add-divorse', AddDivorseView.as_view(), name='add-divorse'),
    path('profile/<pk>', UpdateUserView.as_view(), name='profile'),
    path('find', FindView.as_view(), name='find'),
    path('certificate/success', updateStatus, name='updatestatus')
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

core/urls.py
from os import name
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.static import serve 
from django.conf import settings
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('certification.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/add-couple.html
{% extends 'partiel/base-dash.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content%}
    <div>
        <h3 class="ui" style="background: rgb(13, 156, 234);padding:10px 20px;color: rgb(239, 236, 236);"> Couple Information</h3>
       <form class="ui form" action="" method="post" enctype="multipart/form-data">
           {% csrf_token %}
           <div class="ui  two column grid" >
                <div class="ui twelve wide column ">
                    <h3>Groom Information</h3>
                    {{form|crispy}}
                </div>
           </div>
           <br>
           <div>
               <input class="ui small  fluid  button blue" type="submit" value="Submit">
           </div>
       </form>
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

templates/add-divorse.html
{% extends 'partiel/base-dash.html' %}
{% load static %}
{% block content%}
    <div style="margin-bottom:200px; line-height: 0px;">
        <h3 class="ui" style="background: rgb(13, 156, 234);padding:10px 20px;color: rgb(239, 236, 236);"> Divorse Information</h3>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <form class="ui form" action="" method="post" style="margin-bottom:0px; line-height: 30px;">
           {% csrf_token %}
           <div class="ui   column grid" >
                <div class="ui ten wide column ">
                    {{divorse}}
                </div>
           </div>
            <br>
           <div class="ui ten wide field">
                <input class="ui small  fluid  button blue" type="submit" value="Submit">
           </div>
       </form>
    </div>
{% endblock %}

templates/add-wed.html
{% extends 'partiel/base-dash.html' %}
{% load static %}
{% block content%}
    <div >
        <h3 class="ui" style="background: rgb(13, 156, 234);padding:10px 20px;color: rgb(239, 236, 236);"> Wed Information</h3>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        {% if messageSent %}
            <div>
                <h3>
                    <strong> Email Sucessfully Sent</strong>
                    <p>Your message was sent successfully sent to {{forn.cleaned_data.to}}</p>
                </h3>
            </div>
        {% endif %}
        <form class="ui form" action="" method="post" style="margin-bottom:110px;line-height: 40px;">
           {% csrf_token %}
           <div class="ui  column grid" >
                <div class="ui ten wide column ">
                    {{wed}}
                </div>
           </div>
           
           <br>
           <div class="ui ten wide field">
               <input class="ui  fluid  button blue" type="submit" value="Submit">
           </div>
       </form>
    </div>
    
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Appoint</title>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
<script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
  
    <style type="text/css">
      *, body{
       
      }
      body{
      }
      a{
      }
      .hidden.menu {
        display: none;
      }

  
      .masthead.segment {
        min-height: 520px;
        padding: 1em 0em;
      }
      .masthead .logo.item img {
        margin-right: 1em;
      }
      .masthead .ui.menu .ui.button {
        margin-left: 0.5em;
      }
      .masthead h1.ui.header {
        margin-top: 3em;
        margin-bottom: 0em;
        font-size: 3em;
        font-weight: normal;
      }
      .masthead h2 {
        font-size: 1.7em;
        font-weight: normal;
      }
  
      .ui.vertical.stripe {
        padding: 8em 0em;
      }
      .ui.vertical.stripe h3 {
        font-size: 2em;
      }
      .ui.vertical.stripe .button + h3,
      .ui.vertical.stripe p + h3 {
        margin-top: 3em;
      }
      .ui.vertical.stripe .floated.image {
        clear: both;
      }
      .ui.vertical.stripe p {
        font-size: 1.33em;
      }
      .ui.vertical.stripe .horizontal.divider {
        margin: 2em 0em;
      }
  
      .quote.stripe.segment {
        padding: 0em;
      }
      .quote.stripe.segment .grid .column {
        padding-top: 5em;
        padding-bottom: 5em;
      }
  
      .footer.segment {
        padding: 5em 0em;
      }
  
      .secondary.pointing.menu .toc.item {
        display: none;
      }
  
      @media only screen and (max-width: 700px) {
        .ui.fixed.menu {
          display: none !important;
        }
        .secondary.pointing.menu .item,
        .secondary.pointing.menu .menu {
          display: none;
        }
        .secondary.pointing.menu .toc.item {
          display: block;
        }
        .masthead.segment {
          max-height: 0px;
        }
        .masthead h1.ui.header {
          font-size: 2em;
          margin-top: 1.5em;
        }
        .masthead h2 {
          margin-top: 0.5em;
          font-size: 1.5em;
        }
      }
  
  
    </style>
  
    <script>
    $(document)
      .ready(function() {
  
        // fix menu when passed
        $('.masthead')
          .visibility({
            once: false,
            onBottomPassed: function() {
              $('.fixed.menu').transition('fade in');
            },
            onBottomPassedReverse: function() {
              $('.fixed.menu').transition('fade out');
            }
          })
        ;
  
        // create sidebar and attach to menu open
        $('.ui.sidebar')
          .sidebar('attach events', '.toc.item')
        ;
  
      })
    ;
    </script>
</head>
<body class="ui inverted " style="background: #000 !important;">
    <!-- Following Menu -->
<div class="ui large top fixed hidden  menu">
  <div class="ui container">
    <a href="/" class="active item">Home</a>
    <a class="item">About</a>
    <div class="right item">
      <a href="find" class="ui inverted button">Find Certificate</a>
      <!-- <a class="ui inverted button"></a> -->
    </div>
  </div>
</div>

<!-- Sidebar Menu -->
<div class="ui vertical inverted sidebar menu">
  <  <a href="/" class="active item">Home</a>
  <a class="item">About</a>
  <div class="right item">
    <a href="find" class="ui inverted button">Find Certificate</a>
    <!-- <a class="ui inverted button"></a> -->
  </div>
</div>


<!-- Page Contents -->
    <div class="pusher">
        <div class="ui inverted vertical masthead center aligned segment">
            <div class="ui  inverted container">
                <div class="ui large secondary inverted pointing menu">
                <a class="toc item">
                    <i class="sidebar icon"></i>
                </a>
                <a href="/" class="active item">Home</a>
                <a class="item">About</a>
                <div class="right item">
                    <a href="find" class="ui inverted button">Find Certificate</a>
                    <!-- <a class="ui inverted button"></a> -->
                </div>
                </div>
            </div>

                {%block content%}
                {%endblock%}
            <div class="ui fixed bottom sticky inverted vertical footer segment"
                style="
                padding-top:10px !important;
                padding-bottom:10px !important;width: 100%;
                ">
                <div class="ui container">
                Final Year Project&copy;2021
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/boiler-point.html
{% extends 'partiel/base.html' %}
{% load static %}
{% block content%}

{%endblock%}

templates/dashboard.html
{% extends 'partiel/base-dash.html'%}
{% load static %}
{% block content %}
<style>
</style>
    <div class="stat ui container"> 
        <div class="ui statistics ">
            <div class="statistic">
              <div class="value">
                {{wed_count}}
              </div>
              <div class="label">
                Weddings
              </div>
            </div>
            <div class="statistic">
              <div class=" value">
                {{couple_count}}
              </div>
              <div class="label">
                Couples
              </div>
            </div>
            <div class="statistic">
              <div class="value">
                <i class="heart icon pink" ></i> {{divorse_count}}
              </div>
              <div class="label">
                Divorse
              </div>
            </div>
            <div class="statistic">
              <div class="value">
                <img src="/images/avatar/small/joe.jpg" class="ui circular inline image">
                {{user_count}}
              </div>
              <div class="label">
                Team Members
              </div>
            </div>
          </div>
    </div>
    <hr style="margin-bottom: 15px;">
    <div class="ui container table-wed">
        <h3>
            Weddings Data:
        </h3>
        <div class="ui loading search">
          <form action="" method="GET" class="ui form" >
            <div class="two fields">
                <div class="sixteen wide field" style="display: flex !important; 
                margin:0px 10px; align-items: center !important;
                align-content: space-between !important; ;
                " >
                  {{wed_filter.form}}
                </div>
                <div class="five small field">
                    <input type="submit" value="Search" class="ui button primary" style="">
                </div>
            </div>
          </form>
          <div class="results"></div>
        </div>
        <table class="ui compact celled definition table">
            <thead>
              <tr>
                <th>Wed Matrices</th>
                <th>Couple</th>
                <th>Divorsed</th>
                <th>Registered</th>
                <th>Payment</th>
                <th>Reports</th>
              </tr>
            </thead>
            <tbody>
                {% for weds in wed_filter.qs %}
                    <tr>
                            <td>{{weds.wed_matricule}}</td>
                            <td>{{weds.couple}}</td>
                            <td>{{weds.is_divorsed}}</td>   
                            <td>{{weds.created_at}}</td> 
                            <td>{{weds.payment}}</td>  
                            <td>
                                <a href="dash/certificate/{{weds.wed_matricule}}"><i class="icon red print" style="font-size: 18px;"></i>Print</a> 
                            </td>
                    </tr>    
                    {% empty %}
                    <tr>
                        <th colspan="5">
                            <div class="ui icon message">
                                <i class="notched circle loading icon"></i>
                                <div class="content">
                                  <div class="header">
                                    No Data Found Yet...
                                  </div>
                                  <p>We're fetching that content for you.</p>
                                </div>
                              </div>
                        </th>
                    </tr>          
                {% endfor %}
            </tbody>
            <tfoot class="full-width">
              <tr>
                <th></th>
                <th colspan="5">
                  <div class="ui right floated small blue labeled icon button">
                    <i class="user icon"></i> Register Wedding
                  </div>
                </th>
              </tr>
              <tr><th colspan="5">
                <div class="ui right floated pagination menu">
                  <a class="icon item">
                    <i class="left chevron icon"></i>
                  </a>
                  <a class="item">1</a>
                  <a class="item">2</a>
                  <a class="item">3</a>
                  <a class="item">4</a>
                  <a class="icon item">
                    <i class="right chevron icon"></i>
                  </a>
                </div>
              </th>
            </tr>
            </tfoot>
          </table>
    </div>
    <div class="ui divider"></div>
    <div class="table-Couple">
        <h3>
            Couple Data:
        </h3>
        <div class="ui loading search">
          <div class="ui icon input">
            <input class="prompt" type="text" placeholder="Search Couple">
            <i class="search icon"></i>
          </div>
          <div class="results"></div>
        </div>
        <table class="ui compact celled definition table">
            <thead>
              <tr>
                <th>National ID</th>
                <th>Full Name</th>
                <th>DoB</th>
                <th>Phone</th>
                <th>Mail</th>
                <th>Photo</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
                {% for couples in couple %}
                    <tr>
                        <!-- <td class="collapsing">
                        <div class="ui fitted slider checkbox">
                            <input type="checkbox"> <label></label>
                        </div>
                        </td> -->
                        <td>{{couples.groom_Nat_ID}}/{{couples.bride_Nat_ID}}</td>
                        <td>{{couples.groom_full_name}}/{{couples.bride_full_name}}</td>
                        <td>{{couples.groom_dob|timesince}}/{{couples.bride_dob|timesince}}</td>
                        <td>{{couples.groom_phone}}/{{couples.bride_phone}}</td>
                        <td>{{couples.groom_mail|truncatechars:10}}/{{couples.bride_mail|truncatechars:10}}</td>
                        {% if couples.groom_photo.url and couples.bride_photo.url %}
                            <td><img class="ui avatar image" src="{{couples.groom_photo.url}}" alt="">/<img class="ui avatar image" src="{{couples.bride_photo.url}}" alt=""></td>
                        {% else %}
                            <td><img class="ui avatar image" src="{% static 'images/user.png'%}" alt="">/<img class="ui avatar image" src="{% static 'images/user.png'%}" alt=""></td>
                        {% endif %}
                        <td>{{couples.groom_status}}/{{couples.bride_status}}</td>
                    </tr>  
                    {% empty %}
                    <tr>
                        <th colspan="5">
                            <div class="ui icon message">
                                <i class="notched circle loading icon"></i>
                                <div class="content">
                                    <div class="header">
                                    No Data Found Yet...
                                    </div>
                                    <p>We're fetching that content for you.</p>
                                </div>
                                </div>
                        </th>
                    </tr>           
                {% endfor %}
            </tbody>
            <tfoot class="full-width">
                <tr>
                <th></th>
                <th colspan="7">
                    <div class="ui right floated small blue labeled icon button">
                    <i class="user icon"></i> Register  Couples
                    </div>
                </th>
                </tr>
            </tr>
            </tfoot>
            </table>
    </div>
    <div class="ui divider"></div>
    <div class="table-divorse">
        <h3>
            Divorce Data:
        </h3>
        <div class="ui loading search">
            <div class="ui icon input">
            <input class="prompt" type="text" placeholder="Search Divorce">
            <i class="search icon"></i>
            </div>
            <div class="results"></div>
        </div>
        <table class="ui compact celled definition table">
            <thead>
                <tr>
                <th>Divorce Matricule</th>
                <th>Wedding Matricule</th>
                <th>Sentence</th>
                <th>Magistrate</th>
                <th>Created Date</th>
                <th>Certificate</th>
                </tr>
            </thead>
            <tbody>
                {% for divorses in divorse %}
                    <tr>
                        <td>{{divorses.divorse_matricule}}</td>
                        <td>{{divorses.wed}}</td>
                        <td>{{divorses.sentence}}</td>
                        <td>{{divorses.magistrate}}</td>
                        <td>{{divorses.created_at}}</td>
                        <td><i class="icon red print" style="font-size: 18px;"></i>Print</td>  
                    </tr>
                    {% empty %}
                        <tr>
                            <th colspan="5">
                                <div class="ui icon message">
                                    <i class="notched circle loading icon"></i>
                                    <div class="content">
                                        <div class="header">
                                        No Data Found Yet...
                                        </div>
                                        <p>We're fetching that content for you.</p>
                                    </div>
                                    </div>
                            </th>
                        </tr>
                    {% endfor %}
                <tr>
                </tr>
            </tbody>
            <tfoot class="full-width">
                <tr>
                <th></th>
                <th colspan="5">
                    <div class="ui right floated tiny blue labeled icon button">
                    <i class="user icon"></i> <a class="ui  blue label" href="{% url 'certification:add-divorse'%}">Register Divorse</a> 
                    </div>
                </th>
                </tr>
            </tfoot>
            </table>
    </div>
{% endblock %}

templates/find.html
{% extends "base.html"%}
{% block content %}
    <div class="ui basic modal" id="modal">
        <div class="ui icon header">
        <i class="archive icon"></i>
        Archive Old Messages
        </div>
        <div class="content">
        <p>Your inbox is getting full, would you like us to enable automatic archiving of old messages?</p>
        </div>
        <div class="actions">
        <div class="ui red basic cancel inverted button">
            <i class="remove icon"></i>
            No
        </div>
        <div class="ui green ok inverted button">
            <i class="checkmark icon"></i>
            Yes
        </div>
        </div>
    </div>
    <div class="ui centered column  grid " style="">
        <form action="" class="ui  form" method="post" style="margin:50px !important;">
            {% csrf_token %}
            <div class="" style=" text-align: left !important;line-height: 35px !important;">
                {{form}}
            </div>
            <p>
                <input type="checkbox" name="agree" id="">
                By submitting this form i agree that i've lost my certificate token and i want to get it back via my mail...
            </p>
            
            <div class="field">
                <br>
                <button class="positive ui  fluid button" id="btn">Send Request</button>
            </div>
        </form>
        <button id="btn-1"> click me</button>
    </div>
    <script>
        const model = document.getElementById("modal");
        const btn = document.getElementById("btn-1");
        btn.addEventListener("click", ()=>{
            model.modal('show');
        })

    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
   

  
      <div class="ui text container">
        <h1 class="ui inverted header">
          Online Wedding and divorse Certification
        </h1>
        <h2>Simple way to get you certificate</h2>
        <div class="ui huge blue button"> 
          <a href="{% url 'certification:search' %}" style="color: white;">Find your Certificate Now
            <i class="right arrow icon" style="color: white; margin-left: 10px"></i>
          </a> 
        </div>
      </div>
  
    </div>
  
    <div class="index-main">
      <div class="product-category">
        
      </div>
    </div>
  
    
{% endblock %}

templates/login.html
{% extends 'base.html'%}
{% block content%}
    Login Page
{% endblock%}

templates/payment.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Payment Gateway</title>
            <link rel="stylesheet" href="{% static 'css/style.css'%}">
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
        <script
            src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    </head>
    <body style="overflow:auto">
        <main style="width: 400px; height:300px;margin:auto;background: rgb(243, 239, 239);margin-top:150px;
            padding: 30px 10px;
        ">
            <div>
                <form action="" method="POST">
                    <input type="hidden" name="weds" id="" value="{{pk}}">
                </form>
                <p id="id">{{pk}}</p>
            </div>
            <div id="paypal-button-container"></div>
        </main>
        <script src="https://www.paypal.com/sdk/js?client-id=AVf1mIbS2h14f-VD7LUUPNxrOo0ZWzGtYIfwvp736dwDJwGLMSmQzxfPBIbRsjnl3cW0-jrXsiHqigx6&currency=USD"></script>
        <script>
            function getToken(name) {
                let cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    const cookies = document.cookie.split(';');
                    for (let i = 0; i < cookies.length; i++) {
                        const cookie = cookies[i].trim();
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            const csrftoken = getToken('csrftoken');
            // Render the PayPal button into #paypal-button-container
            const wed_status = true;
            const id = document.querySelector('#id');
            function successOrder(){
					

                url = '{% url "certification:updatestatus" %}';
                

                fetch(url, {
                    method: 'POST',
                    headers: {
                        'Content-type':'application/json',
                        'X-CSRFToken' : csrftoken,
                    },
                    body:JSON.stringify({
                        'status' : wed_status,
                        'id' : id,
                      
                    })
                })
            }
            paypal.Buttons({

                // Set up the transaction
                createOrder: function(data, actions) {
                    return actions.order.create({
                        purchase_units: [{
                            amount: {
                                value: '10.00'
                            }
                        }]
                    });
                },
    
                // Finalize the transaction
                onApprove: function(data, actions) {
                    return actions.order.capture().then(function(orderData) {
                        // Successful capture! For demo purposes:
                        console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                        var transaction = orderData.purchase_units[0].payments.captures[0];
                        alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');
                        
                        successOrder()
                        // Replace the above to show a success message within this page, e.g.
                         const element = document.getElementById('paypal-button-container');
                         element.innerHTML = '';
                         element.innerHTML = '<h3>Thank you for your payment</h3>';
                        actions.redirect('thank_you.html');
                    });
                }
            }).render('#paypal-button-container');
        </script>
    </body>
</html>

templates/profil.html
{% extends 'partiel/base-dash.html' %}
{% load static %}
{% block content%}
<div>
    <h3 class="ui" style="background: rgb(13, 156, 234);padding:10px 20px;color: rgb(239, 236, 236);"> User Information</h3>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <div>
        <a href="{% url 'account_change_password' %}">
            <i class="ui edit icon"></i>Change Password
        </a>
    </div>
    <form class="ui form" action="" method="post" style="margin-bottom:110px;">
       {% csrf_token %}
       <div class="ui   column grid" >
            <div class="ui  column ">
                {{form}}
            </div>
       </div>
       <br>
       <div>
           <input class="ui small  fluid  button blue" type="submit" value="Submit">
       </div>
   </form>
</div>
{% endblock %}

templates/thank_you.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Appoint</title>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
<script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
</head>
<body>
<div class="ui icon header">
    <i class="archive icon"></i>
    Archive Old Messages
  </div>
  <div class="content">
    <p>Your inbox is getting full, would you like us to enable automatic archiving of old messages?</p>
  </div>
  <div class="actions">
    <div class="ui red basic cancel inverted button">
      <i class="remove icon"></i>
      No
    </div>
    <div class="ui green ok inverted button">
      <i class="checkmark icon"></i>
      Yes
    </div>
</div>
</body>
</html>